version: '3.7'

services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile-Client
    command: npm run serve
    volumes:
      - "/app/client/node_modules/"
      - "./vue-portfolio-visualizer-client:/app/client"
    ports:
      - "8080:8080"
    depends_on:
      - api

  api:
    build: 
      context: .
      dockerfile: Dockerfile-Api
    command: npm run serve
    volumes:
      - "/app/api/node_modules/"
      - "./vue-portfolio-visualizer-backend:/app/api/"
    ports:
      - "7070:7070"
    depends_on: 
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vue-portfolio-visualizer-postgres
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  
volumes:
  pgdata:
