FROM node:latest

WORKDIR /app/client
COPY vue-portfolio-visualizer-client/package.json .
COPY vue-portfolio-visualizer-client/package-lock.json .
RUN npm install && npm cache clean --force

COPY vue-portfolio-visualizer-client /app/client
