FROM node:latest

WORKDIR /app/api
COPY vue-portfolio-visualizer-backend/package.json .
COPY vue-portfolio-visualizer-backend/package-lock.json .
RUN npm install && npm cache clean --force

COPY vue-portfolio-visualizer-backend /app/api
